// compta.xls file definition

export const xls_header = [
    // 'chrono'
    'Date',
    // 'mois',
    // 'type',
    'Bénéficiaire',
    // 'info',
    'Nature',
    'n° pièce',

    'BIB', //'autre',
    'PAF',
    'INI', //'initiation',
    'PER', //'perfectionnement',
    'SUB', //'subvention',
    'ADH', //'adhésion',
    'LIC',  //'licence',
    //'droit de table',
    'TAB', //'carte',

    // 'ref carte',

    // 'license',
    // 'FFB',
    // 'Bridge+',
    // 'Formation',
    // 'Matériel',
    // 'PTT',
    // 'Compétitions',
    // 'réunions',
    // 'fêtes',
    // 'café-eau',
    // 'autre',
    // 'banque',

    'Dette',
    'Avoir',

    'Caisse entrée',
    'Caisse sortie',

    'Banque entrée',
    'Banque sortie',

    // 'pointage',
    // 'bordereau',

    // 'verif balance',
    // 'verif dépot',
    // 'verif caisse',
];

export enum COL {
    A = 1,
    B = 2,
    C = 3,
    D = 4,
    E = 5,
    F = 6,
    G = 7,
    H = 8,
    I = 9,
    J = 10,
    K = 11,
    L = 12,
    M = 13,
    N = 14,
    O = 15,
    P = 16,
    Q = 17,
    R = 18,
    S = 19,
    T = 20,
    U = 21,
    V = 22,
    W = 23,
    X = 24,
    Y = 25,
    Z = 26,
    AA = 27,
    AB = 28,
    AC = 29,
    AD = 30,
    AE = 31,
    AF = 32,
    AG = 33,
    AH = 34,
    AI = 35,
    AJ = 36,
    AK = 37,
    AL = 38,
    AM = 39,
    AN = 40,
    AO = 41,
    AP = 42,
}

export const MAP = {
    'chrono': 'A',
    'date': 'B',
    'mois': 'C',
    'membre': 'D',
    'info': 'E',

    'n° carte': 'F',
    'livres': 'G',
    'PAF': 'H',
    'INI': 'I',
    'PER': 'J',
    'Autres': 'K',
    'Adhésion': 'L',
    'Licence': 'M',
    'droit de table': 'N',
    'TAB': 'O',
    'credit_in': 'AB',
    'avoir_in': 'AC',
    'espèces_in': 'AD',
    'banque_in': 'AE',
    'livret_in': 'AF',
    'credit_out': 'AG',
    'avoir_out': 'AH',
    'espèces_out': 'AI',
    'banque_out': 'AJ',
    'livret_out': 'AK',
    'pointage': 'AL',
    'n° chèque': 'AM',
    'bordereau': 'AN',
    'verif balance': 'AO',
    'nature': 'AP',
}

export const PRODUCTS = [
    { col: 'G', name: 'autre', account: 'BIB' },
    { col: 'H', name: 'PAF', account: 'PAF' },
    { col: 'I', name: 'initiation', account: 'INI' },
    { col: 'J', name: 'perf', account: 'PER' },
    { col: 'K', name: 'subvention', account: 'SUB' },
    { col: 'L', name: 'adhesion', account: 'ADH' },
    { col: 'M', name: 'licence', account: 'LIC' },
    { col: 'N', name: 'droit de table', account: 'TAB' },
    { col: 'O', name: 'carte', account: 'CAR' },
];


